### PR TITLE
react-intl: adopt React.JSX types

### PR DESCRIPTION
**Pull request by nstepien**
`react-intl` has a couple type issues when used against React 19 types:
```
> tsc --build

node_modules/react-intl/src/components/provider.d.ts:26:15 - error TS2503: Cannot find namespace 'JSX'.

26     render(): JSX.Element;
                 ~~~

node_modules/react-intl/src/types.d.ts:6:55 - error TS2694: Namespace 'React' has no exported member 'ReactHTML'.

6     textComponent?: React.ComponentType | keyof React.ReactHTML;
                                                        ~~~~~~~~~
```
https://react.dev/blog/2024/04/25/react-19-upgrade-guide#typescript-changes
- `JSX.*` -> `React.JSX.*`
- `React.ReactHTML` doesn't exist anymore, I've replaced it with `React.JSX.IntrinsicElements`.
  - This isn't exactly the same, as it includes svg elements, I couldn't find an alternative with only HTML tag names within React 19 types. Is this OK for react-intl?
  - An alternative may be to use `keyof HTMLElementTagNameMap`.

### CODE REVIEW

**Comment by longlho** [comment]
looks like this requires us to drop React 18 for this to even compile

**Comment by nstepien** [comment]
We use `React.JSX` types fine in our [repos](https://github.com/search?q=repo%3Aadazzle%2Freact-data-grid%20React.JSX&type=code), it just requires the latest version of `@types/react`.

**Review by longlho — APPROVED** [review]

**Comment by longlho** [comment]
merged manually

**Comment by nstepien** [comment]
Thanks!

**Pull request closed without merging**
