### PR TITLE
feat(@formatjs/intl-locale): implement new proposal features for Intl.Locale

### PR DESCRIPTION
**Pull request by wilkmaia**
Proposal: https://github.com/tc39/proposal-intl-locale-info

I've implemented the new features as properties despite [the draft proposal](https://tc39.es/proposal-intl-locale-info/#sec-Intl.Locale.prototype.getCalendars) specifying them as methods. I'm not sure why that is, but I've tested in Safari v16.2 and Google Chrome v110.0.5481.100 and both of them implement them as properties as well.

I've also added some specific tests for the new properties with a few different locales. I didn't have the time to work on a more robust solution and possibly won't be able to do it in the near future.

### CODE REVIEW

**Comment by longlho** [comment]
is this wip?

**Comment by wilkmaia** [comment]
Not at the moment, @longlho. I had to shift my focus for the time being. Meanwhile I'd greatly appreciate feedback on the pending items. Specially on where that info can be found or whether it should be mocked for the time being.

**Comment by simoneb** [comment]
@longlho it's WIP in the sense that it's not complete (feel free to turn this into a draft PR). We'd appreciate feedback about the approach before continuing the implementation.

**Comment by wilkmaia** [comment]
@longlho sorry for not being clearer in my previous message. What I had meant to say is that besides the focus shift I need feedback on the pending items before I can do any more work on this PR.

**Comment by longlho** [comment]
sorry for not getting back earlier. We typically treat `default` as the 1st locale with data loaded (in the cause of `DefaultLocale`). For your cases looks like more locale data is needed, so whichever the 1st dataset that gets loaded that's the default/preferred.
Take a look at `intl-datetimeformat` polyfill for example

**Comment by wilkmaia** [comment]
@longlho do you mean to say there's no need to actively load the data as I've done [here](https://github.com/formatjs/formatjs/pull/3955/files#diff-248037af80a33b4025277d9f62dd1b856b9a6ec1cd4e0300ca601647e34d088d), for instance?

Does that mean that with something like https://github.com/formatjs/formatjs/blob/main/packages/intl-datetimeformat/src/core.ts#LL194-L234C3 we should have access to the missing pieces of info I've mentioned (collations, numbering system, character order) -- assuming that info is included in the dataset for a given locale?

**Comment by wilkmaia** [comment]
@longlho did you catch my last comment?

**Comment by longlho** [comment]
Sorry for the late reply but yeah that's the assumption

**Comment by wilkmaia** [comment]
@longlho FYI this is ready to review now.

**Comment by longlho** [comment]
Thanks a lot for your contributions!

**Pull request merged**
