### PR TITLE
feat(react-intl): move createIntl function to a separate file to support react server components

### LINKED ISSUE #4192: Enable use of 'react-intl' without React Context
## Use case

Currently, `react-intl` components such as `FormattedMessage` cannot be used in React Server Components because of their use of React Context.

The easiest way to encounter this is in a Next.js app using the new App Router.

```tsx
import { FormattedMessage } from "react-intl";

function ServerComponent() {
  return <FormattedMessage id="example" />;
}
```

Trying to use this Server Component we encounter the following exception:

```
Error: createContext only works in Client Components.

Add the "use client" directive at the top of the file to use it. Read more: https://nextjs.org/docs/messages/context-in-server-component
```

## Potential solution

Currently, components like `FormattedMessage` expect to receive an `intl` instance from `useIntl`:

```tsx
function FormattedMessage(props) {
  const intl = useIntl();
  // ...
}
```

The use of React Contexts can be avoided by introducing "contextless alternatives" that receive an `intl` instance as a prop:

```tsx
function FormattedMessageImplementation(props) {
  const intl = props.intl;
  // ...
}

function FormattedMessage(props) {
  const intl = useIntl();
  return <FormattedMessageImplementation {...props} intl={intl} />;
}
```

The contextless alternative could be exposed through a submodule of `react-intl`:

```tsx
import { FormattedMessage } from "react-intl/without-context";
```

This is similar to how `react-i18next` exposes contextless the `Trans`:

```tsx
import { Trans } from "react-i18next/TransWithoutContext";
```

The submodule would also need to expose functions such as `createIntl` because the use of `React.createContext` in the `react-intl/index` barrel causes the same `createContext only works in Client Components` error to occur when importing `createIntl` from `react-intl`.

```tsx
// This encounters the 'createContext only works in Client Components' error

import { createIntl } from "react-intl";

function ServerComponent() {
  const intl = createIntl(...);
}
```

## Alternatives considered

I tried using `createIntl` from `@formatjs/intl` and using that in Server Components:

```tsx
import { createIntl } from "@formatjs/intl";

function ServerComponent() {
  const intl = createIntl({ locale, messages });

  return <p>{intl.formatMessage({ id: "example" })}</p>;
}
```

This approach works for simple messages. However, using `values` encounters type and runtime errors:

```tsx
import { createIntl } from "@formatjs/intl";

function ServerComponent() {
  const intl = createIntl({ locale, messages });

  // Type error: Type 'Element' is not assignable to type 'string | string[]'.
  return (
    <p>
      {intl.formatMessage(
        { id: "example" },
        {
          p: (chunks) => <p>{chunks}</p>,
          code: (chunks) => <code>chunks</code>,
        },
      )}
    </p>
  );
}
```

During runtime, the following warnings are encountered:

```
Warning: Each child in a list should have a unique "key" prop.

Check the top-level render call using <p>. See https://reactjs.org/link/warning-keys for more information.
    at code

Warning: Each child in a list should have a unique "key" prop. See https://reactjs.org/link/warning-keys for more information.
    at p
```

The `createIntl` function from `react-intl` handles these key problems.

## Conclusion

It's currently not possible to use `react-intl` in Server Components.

I would love to hear your thoughts on the proposed solution. I would also be more than willing to help implement this and create a PR.

### PR DESCRIPTION
**Pull request by am1rb**
fix #4192

### CODE REVIEW

**Comment by longlho** [comment]
Thanks a lot for your contributions!

**Comment by turnerhayes** [comment]
When will this change be released in the react-intl NPM package?

**Comment by longlho** [comment]
Should already be out

**Comment by turnerhayes** [comment]
I'm on react-intl@6.6.1 and getting

> createContext only works in Client Components. Add the "use client" directive at the top of the file to use it.

**Comment by am1rb** [comment]
hey @turnerhayes, yep I faced the error again when I tried it on another machine with a different setup, and you are right. it's interesting and at the same time weird that I see no errors in my current project.

you might need to import `createIntl` directly from `react-intl/src/components/createIntl` to avoid the error for now. I recently found [this section](https://github.com/reactjs/rfcs/blob/main/text/0188-server-components.md#sharing-code-between-server-and-client) on RSC rfs and think using [Conditional exports](https://github.com/reactjs/rfcs/blob/main/text/0227-server-module-conventions.md#react-server-conditional-exports) we can resolve the importing problem.

I might raise a new PR in the future soon to address the problem if no one else is working on it yet.

**Pull request merged**
