### PR TITLE
Add check whether Intl defined

### PR DESCRIPTION
**Pull request by vlazh**

### CODE REVIEW

**Comment by longlho** [comment]
This check is being done in `Intl.getCanonicalLocales` since it's the 1st one in the hierarchy https://formatjs.io/docs/polyfills

**Comment by vlazh** [comment]
Without this chech I can't load polyfills in parallel. Relativedateformat has this check, why?

**Comment by vlazh** [comment]
As I can see, almost all polyfills have this check. What's wrong with adding it here too?

**Comment by longlho** [comment]
@vlazh you're not supposed to load these polyfills in parallel as they depend on one another. If you're doing that right now there'll be race condition and your app will crash.
The correct fix is actually to remove the `Intl` checks in all polyfills except `Intl.getCanonicalLocales`

**Comment by vlazh** [comment]
I load all polyfills in parallel now with Promise.all and it works fine. After that I load data. Without this chech I need to create Intl var before loading. It's too long to load polyfills synchronously. I tried that variant and it's not good user experience.

**Pull request closed without merging**
