### PR TITLE
feat(@formatjs/swc-plugin-experimental): add Bazel rules for swc-plugin-experimental

### PR DESCRIPTION
**Pull request by pyrocat101**
This PR introduces the Bazel rules that can build rust crates for swc-plugin-formatjs, as well as cross-compilation to WASM for npm distribution.

### CODE REVIEW

**Comment by pyrocat101** [comment]
@kwonoj This might be a long shot. But I am having trouble getting the SWC plugin to work.

To reproduce, try `bazel test --sandbox_debug //packages/swc-plugin-formatjs:test_plugin`.

This is the crash I got from a M1 mac:

```
==================== Test output for //packages/swc-plugin-formatjs:test_plugin:
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: LayoutError', ./external/swc_plugin_formatjs_crate_index__rkyv-0.7.37/src/impls/core/mod.rs:265:67
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'failed to invoke plugin: failed to invoke plugin on 'Some("/private/var/tmp/_bazel_user/9e1951504fb57c164ef25d9cd369bb16/sandbox/darwin-sandbox/3253/execroot/formatjs/bazel-out/darwin_arm64-fastbuild/bin/packages/swc-plugin-formatjs/test_plugin.sh.runfiles/formatjs/packages/swc-plugin-formatjs/spec/fixtures/additionalComponentNames.js")'

Caused by:
    0: failed to invoke `/private/var/tmp/_bazel_user/9e1951504fb57c164ef25d9cd369bb16/sandbox/darwin-sandbox/3253/execroot/formatjs/bazel-out/darwin_arm64-fastbuild/bin/packages/swc-plugin-formatjs/test_plugin.sh.runfiles/formatjs/packages/swc-plugin-formatjs/swc_plugin_formatjs.wasm` as js transform plugin at /private/var/tmp/_bazel_user/9e1951504fb57c164ef25d9cd369bb16/sandbox/darwin-sandbox/3253/execroot/formatjs/bazel-out/darwin_arm64-fastbuild/bin/packages/swc-plugin-formatjs/test_plugin.sh.runfiles/formatjs/packages/swc-plugin-formatjs/swc_plugin_formatjs.wasm
    1: RuntimeError: call stack exhausted
    2: stk_ovf', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/swc-0.232.20/src/plugin.rs:228:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by pyrocat101** [comment]
@kwonoj This might be a long shot. But I am having trouble getting the SWC plugin to work.

To reproduce, try `bazel test --sandbox_debug //packages/swc-plugin-formatjs:test_plugin`.

This is the crash I got from a M1 mac:

```
==================== Test output for //packages/swc-plugin-formatjs:test_plugin:
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: LayoutError', ./external/swc_plugin_formatjs_crate_index__rkyv-0.7.37/src/impls/core/mod.rs:265:67
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'failed to invoke plugin: failed to invoke plugin on 'Some("/private/var/tmp/_bazel_user/9e1951504fb57c164ef25d9cd369bb16/sandbox/darwin-sandbox/3253/execroot/formatjs/bazel-out/darwin_arm64-fastbuild/bin/packages/swc-plugin-formatjs/test_plugin.sh.runfiles/formatjs/packages/swc-plugin-formatjs/spec/fixtures/additionalComponentNames.js")'

Caused by:
    0: failed to invoke `/private/var/tmp/_bazel_user/9e1951504fb57c164ef25d9cd369bb16/sandbox/darwin-sandbox/3253/execroot/formatjs/bazel-out/darwin_arm64-fastbuild/bin/packages/swc-plugin-formatjs/test_plugin.sh.runfiles/formatjs/packages/swc-plugin-formatjs/swc_plugin_formatjs.wasm` as js transform plugin at /private/var/tmp/_bazel_user/9e1951504fb57c164ef25d9cd369bb16/sandbox/darwin-sandbox/3253/execroot/formatjs/bazel-out/darwin_arm64-fastbuild/bin/packages/swc-plugin-formatjs/test_plugin.sh.runfiles/formatjs/packages/swc-plugin-formatjs/swc_plugin_formatjs.wasm
    1: RuntimeError: call stack exhausted
    2: stk_ovf', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/swc-0.232.20/src/plugin.rs:228:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

<MORE OUTPUT OMITTED>
```

**Comment by kwonoj** [comment]
Not all of the cases, but sometimes matching @swc/core version to the plugin resolves this issue time to time.

**Comment by mansona** [comment]
So I've been struggling to run tests locally and I needed to make these changes to make them work https://github.com/formatjs/formatjs/pull/3914

I guess that might vibe with what you're saying @kwonoj since I had to update swc things to get it to work 👍

**Pull request merged**
