### PR TITLE
fix(@formatjs/intl-getcanonicallocales): fix import path for polyfills

### PR DESCRIPTION
**Pull request by hustcer**
Fix import path for polyfills

### CODE REVIEW

**Comment by longlho** [comment]
What's the issue you're having?

**Comment by hustcer** [comment]
> What's the issue you're having?

When I import the polyfill by:
```javascript
import '@formatjs/intl-getcanonicallocales/polyfill'
import '@formatjs/intl-pluralrules/polyfill'
import '@formatjs/intl-pluralrules/locale-data/zh'
import '@formatjs/intl-pluralrules/locale-data/en'
import '@formatjs/intl-numberformat/polyfill'
import '@formatjs/intl-numberformat/locale-data/zh'
import '@formatjs/intl-numberformat/locale-data/en'
import '@formatjs/intl-relativetimeformat/polyfill';
import '@formatjs/intl-relativetimeformat/locale-data/zh';
import '@formatjs/intl-relativetimeformat/locale-data/en';
import '@formatjs/intl-listformat/polyfill';
import '@formatjs/intl-listformat/locale-data/en';
import '@formatjs/intl-listformat/locale-data/zh';
import '@formatjs/intl-displaynames/polyfill';
import '@formatjs/intl-displaynames/locale-data/en';
import '@formatjs/intl-displaynames/locale-data/zh';
import '@formatjs/intl-datetimeformat/polyfill'
import '@formatjs/intl-datetimeformat/locale-data/zh'
import '@formatjs/intl-datetimeformat/locale-data/en'
import '@formatjs/intl-locale/polyfill';
```
In my ReactNative Apps, the error displayed as follows:

image

The intl-getcanonicallocales polyfill seems not work. After adding patches above, they work fine.

**Comment by hustcer** [comment]
BTW: It's reasonable to follow the same import style just as `intl-datetimeformat` does right?

**Comment by longlho** [comment]
Did you confirm this fixes your issue?

**Comment by hustcer** [comment]
> Did you confirm this fixes your issue?

Yes, it does. What's more, the following warnings disappeared:

Screen Shot 2020-11-26 at 09 25 17

**Comment by longlho** [comment]
Thanks a lot for your contributions!

**Pull request merged**
