### PR TITLE
Remove Jest, prepare for Vitest

### PR DESCRIPTION
**Pull request by NullVoxPopuli**
Jest's lack of proper support for mjs files in cjs projects is blocking: https://github.com/formatjs/formatjs/pull/4376 (everything is fine at runtime, which is extra frustrating)

Here I try removing jest altogether.
I did see that there is a jest-specific package (a transformer), so I'll need to re-add jest to that package, but in general, it seems that this is making things much simpler (so far).

### CODE REVIEW

**Comment by longlho** [comment]
`vitest` needs to work with bazel so this PR won't work. Let me take a stab at this myself

**Comment by NullVoxPopuli** [comment]
Locally things aren't ready yet, so idk how much time you want to spend on this 😅

**Comment by longlho** [comment]
I spent some time and it's non-trivial, likely because `vitest` isn't entirely hermetic. The tricky thing is to deal w/ snapshots testing & update which https://github.com/aspect-build/rules_jest handles for us already.

**Comment by NullVoxPopuli** [comment]
Is the aspect needed? Running vitest from the repo root seems to find tests in all the sub packages?

**Comment by longlho** [comment]
closing this for now since this unlikely is going to happen.

**Comment by NullVoxPopuli** [comment]
yeah, I think first, perhaps bazel would need to be removed :thinking: 

or someone that knows bazel better would need to take on this work

**Pull request closed without merging**
