### PR TITLE
feat(@formatjs/icu-messageformat-parser): preprocess 'j' date time skeleton before parsing as suggested in the Unicode guide

### PR DESCRIPTION
**Pull request by batjaa**
- Preprocess 'j' date time skeleton before parsing as suggested in the [Unicode guide](https://www.unicode.org/reports/tr35/tr35-dates.html#table-mapping-requested-time-skeletons-to-patterns)
- Add unit tests & tests for `intl-messageformat` for date time skeleton 'j' patterns

### CODE REVIEW

**Comment by batjaa** [comment]
@longlho would you approve the tests/builds?

**Comment by batjaa** [comment]
Fixed broken build:
- IDE automatically formatted some part of snapshot file
- Run prettier to fix styling issues

@longlho if you can approve for builds again. Do I need to request building everytime I make a change?

**Comment by longlho** [comment]
Unfortunately yeah because it's your first PR

**Comment by batjaa** [comment]
Got it. All good, just wanted to confirm.
- Fix unit tests :duh:

**Comment by longlho** [comment]
Thanks a lot for your contributions!

**Comment by batjaa** [comment]
👍  I'll try to contribute more as time allows.

**Pull request merged**
