### PR TITLE
fix(@formatjs/intl-enumerator): fixes intl.supportedValuesOf units

### PR DESCRIPTION
**Pull request by micheleriva**
This is a follow-up PR for #3694. This fixes the `units` values by following the official [ECMA standard](https://tc39.es/ecma402/#table-sanctioned-simple-unit-identifiers).

As stated in PR #3694, it was mainly a porting of the official TC39 proposal, which evolved over time, while the polyfills have not been updated. Thanks for spotting this @longlho!

### CODE REVIEW

**Comment by longlho** [comment]
this is a tricky one, because the [spec](https://tc39.es/ecma402/#sec-iswellformedunitidentifier) says that if unit X is santioned & Y is sanctioned, then `X-per-Y` and `Y-per-X` are also well-formed. Check out https://github.com/formatjs/formatjs/blob/main/packages/ecma402-abstract/IsWellFormedUnitIdentifier.ts & https://github.com/formatjs/formatjs/blob/main/packages/ecma402-abstract/IsSanctionedSimpleUnitIdentifier.ts for the implementation of those operations

**Comment by longlho** [comment]
I just checked chrome and looks like they don't care about `-per-` unit so you can actually just use `SIMPLE_UNITS` from `@formatjs/ecma402-abstract`

**Comment by micheleriva** [comment]
@longlho fixed, I also added the following comments to each generated output:

```
/* @generated */
// prettier-ignore
```

without this, if you ran prettier on the whole codebase, it gives you conflicts after re-generating files. I noticed that these comments are already used in other scripts, so now they're all consistent

**Comment by longlho** [comment]
Thanks a lot for your contributions!

**Pull request merged**
