### PR TITLE
feat(react-intl): allow setting a stricter type for message IDs

### PR DESCRIPTION
**Pull request by GuilleDF**
This allows specifying the type that will be used for message IDs to something stricter than `string`. That way, you can check at compile time that the ids passed to `<FormattedMessage />` and `formatMessage` actually exist in your translation files. You also get the added benefit of auto-complete if you're in an IDE 😃 

An example on how to use this:
```tsx
const messages = {
  greeting: 'Hello',
  planet: 'World',
};

// Set the following type:
declare global {
  namespace FormatjsIntl {
    interface Message {
      ids: keyof typeof messages
    }
  }
}

const App = () => (
  <IntlProvider messages={messages}>
    <FormattedMessage id="greeting" />
    <FormattedMessage id="planet" />
  </IntlProvider>
);
```

I tried to implement this by inferring the type from the messages passed to the `IntlProvider` component, but given that an app could have several providers, we would need a way for Typescript to know which is the closest provider ancestor. I don’t think Typescript has any way of inferring that information.

I also added an example in the `react-intl` package, but I'm not sure if it's the best place to put it, so I'm happy to move it somewhere else 😃 

Also, I wasn’t sure which would be the best name for the global namespace, so I'm happy to change it from `FormatjsIntl.Message` to something else as well.

### CODE REVIEW

**Comment by longlho** [comment]
Thanks a lot for your contributions! I'll try to look asap

**Comment by longlho** [comment]
sorry for taking a while, would you mind updating our docs as well? (under `website/docs/react-intl.md`)

**Comment by GuilleDF** [comment]
> sorry for taking a while, would you mind updating our docs as well? (under `website/docs/react-intl.md`)

No worries, no rush! 😄 
I added the docs

**Comment by longlho** [comment]
Thanks a lot for your contributions!

**Pull request merged**
