### PR TITLE
docs: orama version

### PR DESCRIPTION
**Pull request by ilteoood**
This should fix the issues with orama and the deployed website

### CODE REVIEW

**Comment by ilteoood** [comment]
@longlho if we can restore the search functionality it would be awesome 🙏

**Comment by longlho** [comment]
Thanks a lot for your contributions!

**Comment by HarrisonLeach1** [comment]
Hey @longlho 👋, was the website deployed again with this fix? Search seems to be broken still

**Comment by longlho** [comment]
It's deployed but looks like orama has some compat issue with docusaurus. I haven't got a chance to look yet.

**Pull request merged**
