### PR TITLE
Update tzdata to 2023c

### PR DESCRIPTION
**Pull request by davidseek**
I have updated `tzdata` to `2023c` as described in the [CONTRIBUTION Wiki](https://github.com/formatjs/formatjs/blob/main/CONTRIBUTING.md#updating-tzdata-version), including updating the sha and running the Bazel script. The Commit is the result of that script.

### CODE REVIEW

**Comment by davidseek** [comment]
Follow up to https://github.com/formatjs/formatjs/pull/4043

**Comment by davidseek** [comment]
Unit tests failed because of this: 

```
node_modules/fast-glob/out/types/index.d.ts(2,25): error TS2307: Cannot find module '@nodelib/fs.walk' or its corresponding type declarations.
```

**Comment by davidseek** [comment]
I have added the [Commit](https://github.com/formatjs/formatjs/pull/4065/commits/d29cb6534d335958fac3727eb16dbc425167ba1b) to update the outdated TimeZones as discussed. Additionally, I have updated the Contribution Wiki with a hint to do the same next time, when updating to a new `tzdata` version.

**Comment by longlho** [comment]
@davidseek can u make a new PR? I'm trying to fix our CI pipeline

**Comment by davidseek** [comment]
@longlho, created new request https://github.com/formatjs/formatjs/pull/4072

**Pull request closed without merging**
