### PR TITLE
fix(react-intl): add generic constraint to defineMessage for better intellisense experience

### PR DESCRIPTION
**Pull request by mvestergaard**
Currently, when writing:
```ts
const message = defineMessage({ defaultMessage: 'Some message' });
```
There is no autocomplete presented for the thing passed to `defineMessage`.

That only happens if you either are passing it to something that already expected a `MessageDescriptor` such as `intl.formatMessage`, or type the variable explicitly, such as:
```ts
const message: MessageDescriptor = defineMessage(...);
```

I don't know if there's any specific reason why you typed it the way it was, but if not, then I would suggest that this gives a better developer experience.

### CODE REVIEW

**Comment by longlho** [comment]
Thanks a lot for your contributions!

**Comment by SRachamim** [comment]
This "patch version" contains a severe breaking change to the type signature of `defineMessage`, which is in the public interface . It should have triggered a major bumping.

Please be careful and respect semantic versioning.

**Comment by mvestergaard** [comment]
@SRachamim I'm curious. Can you demonstrate a scenario where this is a breaking change? I thought of it as quite harmless when I suggested it.

**Comment by SRachamim** [comment]
When you `extends` a type parameter, you actually narrow down the possible types it can adhere to (in this case, from `unknown` to `MessageDescriptor`).

We had many places that inaccurately used `defineMessage` instead of `defineMessages`. It worked for us both at the type level and on runtime.

Since that "patch" version, it stopped working on the type level. Which broke compilation of code that used to compiled successfully. Which is a breaking change.

**Comment by mvestergaard** [comment]
So you're saying it broke unintended usage? Is that really a breaking change?

**Comment by SRachamim** [comment]
Technically - it is. Documentation is out of scope in this discussion, so "unintended" usage is not accurate here. Type-wise (and also runtime-wise) - `defineMessage` was used correctly.

Semantic versioning is a community standard, and its purpose is to prevent breaking consumers on non-major versions.

This change broke at least one consumer. :)

**Comment by mvestergaard** [comment]
By that logic, any bug fix can be a breaking change, if anyone relies on it in a way it wasn't intended, just because it was possible. It's quite difficult to predict if anything will break in that scenario.

**Comment by SRachamim** [comment]
It's very easy to predict it, and can even be automated. It's a type signature of a function on the public interface - any change that narrows or changes the public interface (for good or bad) is a breaking one.

Widening a type parameter, for example, is not a breaking change.

**Comment by SRachamim** [comment]
Thanks for this commit anyway!  ❤️

**Comment by longlho** [comment]
We don't bump major for type changes, only for runtime breaking changes.

**Comment by SRachamim** [comment]
That's sad, but legit, as long as you mention you don't follow semantic versioning.

**Comment by longlho** [comment]
Yeah we don't strictly follow semantic versioning. You should always pin to a version u've tested

**Comment by SRachamim** [comment]
Npm assumes semantic versioning. Most of your users will use `npm i`, which doesn't pin as you just asked me.

If the package doesn't follow semantic versioning then it's best to mention it as the first line in `README.md`.

https://docs.npmjs.com/about-semantic-versioning

**Comment by longlho** [comment]
Npm doesn't follow anything. Your should have lock file and tests

**Comment by SRachamim** [comment]
I didn't say "follow", I said "assume", which you can test yourself by trying to install the package yourself and see a caret in there. Consumers won't remove this caret if you won't ask them to.

You're right, because packages that don't follow semver exist we need things like `yarn.lock`, but it's not bullet proof because it'll  change from time to time due to installations of other packages. They will get generated from scratch from time to time. Anyway users will need to know they have to pin their versions even to patch releases. And that's why it's advisable to mention it on the readme.

Tests won't cover all types of breaking change (including this specific one we're talking about) and they don't need to be broken at all by a patch version.

Anyway, I know what should I do in case you don't follow semver, just saying your users need to know they should do it.

**Pull request merged**
