### PR TITLE
docs: improve documentation around `ts-transformer`

### PR DESCRIPTION
**Pull request by arawden**
I've fixed a small bug in the README and added some preliminary attempts at improving the documentation for the `ts-transformer` pacakge on the website.

I wanted to expand a little bit on the areas highlighted in [this comment](https://github.com/formatjs/formatjs/issues/2110#issuecomment-710180203), but I wasn't sure what to write. I started by using the comments from the source

https://github.com/formatjs/formatjs/blob/47866eb932e05087bbf1aaa03032b69e3664c401/packages/ts-transformer/src/transform.ts#L100-L125

I've marked this as a draft because I imagine it will need some improvement before it can be fully merged. Specifically, I'd ask for guidance as to how to move the documentation away from implementation details and more towards a broad, helpful explanation of the options for the transformer.

### CODE REVIEW

**Comment by longlho** [comment]
This lgtm. Thanks for the PR!
In terms of 'idInterpolationPattern' I'll prob keep using `overrideIdFn` otherwise we get into scenario where both are set and have to decide which one takes over.

**Comment by unframework** [comment]
Should the `idInterpolationPattern` blurb be removed from the ts-transformer doc then? It does not look like this parameter is used in ts-transformer currently at all.

@longlho re: your comment about using `overrideIdFn` - other tooling uses `idInterpolationPattern` instead, is that correct? How closely would you want to replicate that flag naming in this context for consistency?

**Comment by longlho** [comment]
yes it should be removed from the doc. The reason for `idInterpolationPattern` vs `overrideIdFn` is bc typescript doesn't have a plugin API so when this was created the only way to use it was to write a wrapper around the TS compiler API. We can technically make a breaking change but idk if it's worth it.

**Comment by arawden** [comment]
I went ahead and removed the `idInterpolationPattern` portion from the `ts-transformer` docs, and marked the PR as ready for review.

I think the only thing I'd want to add would be an example of `overrideIdFn` with a function, as the docs seem to mostly showcase it being used with a string pattern.

**Comment by longlho** [comment]
If you use overrideIdFn programmatically typescript definition will kick in that tells you what params there are

**Comment by longlho** [comment]
Thanks a lot for your contributions!

**Pull request merged**
