### PR TITLE
fix: add actual default message to Missing translation

### LINKED ISSUE #3573: Adding the actual message in MISSING_TRANSLATION error
## Which package?
`@format/intl`

## Describe the bug

This is more like a feature request.
Currently, when getting `MISSING_TRANSLATION` error on the browser, it prints console error like this:

```js
[@formatjs/intl Error MISSING_TRANSLATION] Missing message: "lJOsMK" for locale "en-US", using default message as fallback.
```

Since the id is a hash, it would be very hard to find out which message is missing the translation.

I ran the extract command: `formatjs extract 'src/**/*.ts*' --ignore='**/*.d.ts' --out-file lang/en.json --id-interpolation-pattern '[sha512:contenthash:base64:6]'`
but it does not produce an entry with ID `IJOsMK`.

It would be great if we can add the actual message to the error so that it will be much easier to find exactly what is the problem.

e.g.:

```js
[@formatjs/intl Error MISSING_TRANSLATION] Missing message: "lJOsMK" for locale "en-US", using default message "some not translated message" as fallback.
```

## To Reproduce

Since I can't figure out what was the problem, and the project is private, I can't create a repro on this.

## Expected behavior

Make it easier to find what is the offending message.

### PR DESCRIPTION
**Pull request by unional**
fixes #3573

### CODE REVIEW

**Comment by unional** [comment]
Currently this PR prints `([object object])` which is not helpful. I'll make an adjustment

**Comment by unional** [comment]
Um... I notice the repo doesn't work in Windows or WSL environment.

In Windows:

```sh
INFO: Repository npm instantiated at:
  D:/code/unional/formatjs/WORKSPACE:57:12: in <toplevel>
  C:/users/homa/_bazel_homa/2bjmlqta/external/build_bazel_rules_nodejs/index.bzl:78:17: in npm_install
Repository rule npm_install defined at:
  C:/users/homa/_bazel_homa/2bjmlqta/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl:775:30: in <toplevel>
ERROR: An error occurred during the fetch of repository 'npm':
   Traceback (most recent call last):
        File "C:/users/homa/_bazel_homa/2bjmlqta/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 752, column 13, in _npm_install_impl
                fail("npm_install failed: %s (%s)" % (result.stdout, result.stderr))
Error in fail: npm_install failed: 
> formatjs-repo@1.0.0 postinstall
> husky install && patch-package

 (npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
The system cannot find the path specified.
npm ERR! code 1
npm ERR! path C:\Users\homa\_bazel_homa\2bjmlqta\external\npm\_
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c husky install && patch-package

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\homa\AppData\Local\npm-cache\_logs\2022-04-30T20_45_16_591Z-debug.log
)
ERROR: Error fetching repository: Traceback (most recent call last):                                                                                                                                                   
        File "C:/users/homa/_bazel_homa/2bjmlqta/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 752, column 13, in _npm_install_impl                                                    
                fail("npm_install failed: %s (%s)" % (result.stdout, result.stderr))
Error in fail: npm_install failed:
> formatjs-repo@1.0.0 postinstall
> husky install && patch-package

 (npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
The system cannot find the path specified.
npm ERR! code 1
npm ERR! path C:\Users\homa\_bazel_homa\2bjmlqta\external\npm\_
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c husky install && patch-package

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\homa\AppData\Local\npm-cache\_logs\2022-04-30T20_45_16_591Z-debug.log
)
ERROR: no such package '@npm//test262-harness': npm_install failed:                                                                                                                                                    
> formatjs-repo@1.0.0 postinstall                                                                                                                                                                                      
> husky install && patch-package

 (npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
se a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.The system cannot find the path specified.
npm ERR! code 1
npm ERR! path C:\Users\homa\_bazel_homa\2bjmlqta\external\npm\_
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c husky install && patch-package

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\homa\AppData\Local\npm-cache\_logs\2022-04-30T20_45_16_591Z-debug.log
)
INFO: Elapsed time: 39.832s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
```

In WSL:

```sh
Starting local Bazel server and connecting to it...
INFO: Invocation ID: de6f3016-eff1-4358-9028-3ba128273d59
INFO: Repository ubuntu2110 instantiated at:
  /mnt/d/code/unional/formatjs/WORKSPACE:182:15: in <toplevel>
Repository rule container_pull defined at:
  /home/homa/.cache/bazel/_bazel_homa/13878f1363f589b42f2fa5f84b9208a1/external/io_bazel_rules_docker/container/pull.bzl:278:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'ubuntu2110':
   Traceback (most recent call last):
        File "/home/homa/.cache/bazel/_bazel_homa/13878f1363f589b42f2fa5f84b9208a1/external/io_bazel_rules_docker/container/pull.bzl", line 224, column 13, in _impl
                fail("Pull command failed: %s (%s)" % (result.stderr, " ".join([str(a) for a in args])))
Error in fail: Pull command failed: 2022/04/30 13:41:52 Running the Image Puller to pull images from a Docker Registry...
2022/04/30 13:41:52 Image pull was unsuccessful: reading image "index.docker.io/library/ubuntu@sha256:d0b4808a158b42b6efb3ae93abb567b1cb6ee097221813c0315390de0fa320b9": error getting credentials - err: exec: "docker-credential-desktop.exe": executable file not found in $PATH, out: ``
 (/home/homa/.cache/bazel/_bazel_homa/13878f1363f589b42f2fa5f84b9208a1/external/go_puller_linux_amd64/file/downloaded -directory /home/homa/.cache/bazel/_bazel_homa/13878f1363f589b42f2fa5f84b9208a1/external/ubuntu2110/image -os linux -os-version  -os-features  -architecture amd64 -variant  -features  -name index.docker.io/library/ubuntu@sha256:d0b4808a158b42b6efb3ae93abb567b1cb6ee097221813c0315390de0fa320b9)
ERROR: Error fetching repository: Traceback (most recent call last):
        File "/home/homa/.cache/bazel/_bazel_homa/13878f1363f589b42f2fa5f84b9208a1/external/io_bazel_rules_docker/container/pull.bzl", line 224, column 13, in _impl
                fail("Pull command failed: %s (%s)" % (result.stderr, " ".join([str(a) for a in args])))
Error in fail: Pull command failed: 2022/04/30 13:41:52 Running the Image Puller to pull images from a Docker Registry...
2022/04/30 13:41:52 Image pull was unsuccessful: reading image "index.docker.io/library/ubuntu@sha256:d0b4808a158b42b6efb3ae93abb567b1cb6ee097221813c0315390de0fa320b9": error getting credentials - err: exec: "docker-credential-desktop.exe": executable file not found in $PATH, out: ``
 (/home/homa/.cache/bazel/_bazel_homa/13878f1363f589b42f2fa5f84b9208a1/external/go_puller_linux_amd64/file/downloaded -directory /home/homa/.cache/bazel/_bazel_homa/13878f1363f589b42f2fa5f84b9208a1/external/ubuntu2110/image -os linux -os-version  -os-features  -architecture amd64 -variant  -features  -name index.docker.io/library/ubuntu@sha256:d0b4808a158b42b6efb3ae93abb567b1cb6ee097221813c0315390de0fa320b9)
INFO: Repository remote_java_tools_linux instantiated at:
  /DEFAULT.WORKSPACE.SUFFIX:223:6: in <toplevel>
  /home/homa/.cache/bazel/_bazel_homa/13878f1363f589b42f2fa5f84b9208a1/external/bazel_tools/tools/build_defs/repo/utils.bzl:201:18: in maybe
Repository rule http_archive defined at:
  /home/homa/.cache/bazel/_bazel_homa/13878f1363f589b42f2fa5f84b9208a1/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
INFO: Repository remotejdk11_linux instantiated at:
  /DEFAULT.WORKSPACE.SUFFIX:52:6: in <toplevel>
  /home/homa/.cache/bazel/_bazel_homa/13878f1363f589b42f2fa5f84b9208a1/external/bazel_tools/tools/build_defs/repo/utils.bzl:201:18: in maybe
Repository rule http_archive defined at:
  /home/homa/.cache/bazel/_bazel_homa/13878f1363f589b42f2fa5f84b9208a1/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: /mnt/d/code/unional/formatjs/BUILD:197:13: //:ubuntu_build_essential_image depends on @ubuntu2110//image:image in repository @ubuntu2110 which failed to fetch. no such package '@ubuntu2110//image': Pull command failed: 2022/04/30 13:41:52 Running the Image Puller to pull images from a Docker Registry...
2022/04/30 13:41:52 Image pull was unsuccessful: reading image "index.docker.io/library/ubuntu@sha256:d0b4808a158b42b6efb3ae93abb567b1cb6ee097221813c0315390de0fa320b9": error getting credentials - err: exec: "docker-credential-desktop.exe": executable file not found in $PATH, out: ``
 (/home/homa/.cache/bazel/_bazel_homa/13878f1363f589b42f2fa5f84b9208a1/external/go_puller_linux_amd64/file/downloaded -directory /home/homa/.cache/bazel/_bazel_homa/13878f1363f589b42f2fa5f84b9208a1/external/ubuntu2110/image -os linux -os-version  -os-features  -architecture amd64 -variant  -features  -name index.docker.io/library/ubuntu@sha256:d0b4808a158b42b6efb3ae93abb567b1cb6ee097221813c0315390de0fa320b9)
ERROR: Analysis of target '//:tz_install' failed; build aborted: Analysis failed
INFO: Elapsed time: 65.778s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1682 packages loaded, 97230 targets configured)
FAILED: Build did NOT complete successfully (1682 packages loaded, 97230 targets configured)
    Fetching @com_github_bazelbuild_buildtools; Restarting. 15s
    Fetching @bazel_gazelle_go_repository_config; Restarting. 15s
    Fetching @bazel_gazelle_go_repository_tools; fetching 5s
    Fetching @com_github_google_go_containerregistry; Restarting. 4s
    Fetching @com_github_pkg_errors; Restarting. 4s
```

The WSL one I might able to do something by getting docker inside WSL.

**Comment by unional** [comment]
Please let me know if you are ok with this simple print out or you want to use the `printAST()` function.

I'm not sure if that would make sense in this context.

**Comment by unional** [comment]
FYI I try to get it work in WSL but no luck.

It also needs python so I added python3 (from `brew install python`) and add symlink (`ln -s /usr/bin/python3 /usr/local/bin/python`).

But then it still complain about docker, which I do by setting up the docker with WSL.

Here is the error:

```sh
> bazel test //...

INFO: Invocation ID: 77693e84-d626-48bb-a331-a6029d51fbc0
INFO: Analyzed 957 targets (0 packages loaded, 0 targets configured).
INFO: Found 714 targets and 243 test targets...
ERROR: /mnt/d/code/unional/formatjs/BUILD:189:14: Action build_essential_pkgs.tar [for host] failed: (Exit 1): build_essential_pkgs.sh failed: error executing command
  (cd /home/homa/.cache/bazel/_bazel_homa/13878f1363f589b42f2fa5f84b9208a1/sandbox/linux-sandbox/854/execroot/formatjs && \
  exec env - \
    PATH=/bin:/usr/bin:/usr/local/bin \
  bazel-out/host/bin/build_essential_pkgs.sh)
Execution platform: @local_config_platform//:host

Use --sandbox_debug to see verbose messages from the sandbox
error: docker not found; do you need to manually configure the docker toolchain?
ERROR: /mnt/d/code/unional/formatjs/packages/intl-datetimeformat/BUILD:239:10 Action packages/intl-datetimeformat/add-all-tz.js failed: (Exit 1): build_essential_pkgs.sh failed: error executing command
  (cd /home/homa/.cache/bazel/_bazel_homa/13878f1363f589b42f2fa5f84b9208a1/sandbox/linux-sandbox/854/execroot/formatjs && \
  exec env - \
    PATH=/bin:/usr/bin:/usr/local/bin \
  bazel-out/host/bin/build_essential_pkgs.sh)
Execution platform: @local_config_platform//:host

Use --sandbox_debug to see verbose messages from the sandbox
INFO: Elapsed time: 3.450s, Critical Path: 0.11s
INFO: 77 processes: 1 remote cache hit, 75 internal, 1 local.
FAILED: Build did NOT complete successfully
```

**Comment by unional** [comment]
Since this repo is using prettier and I'm not,

I'm also added the setting in the vscode settings to set the formatter to prettier.

**Comment by longlho** [comment]
Thanks a lot for your contributions!

**Pull request merged**
