### PR TITLE
fix(@formatjs/ecma402-abstract): limit accepted calendar values to 'gregory'

### LINKED ISSUE #2616: Type issue with TS 4.2
## Which package?
`@formatjs/ecma402-abstract` via `react-intl`

## Describe the bug
With TypeScript 4.2 (currently in release candidate), there is a type issue:
```
node_modules/@formatjs/ecma402-abstract/types/date-time.d.ts:1:18 - error TS2430: Interface 'import("D:/repos/MediaModule/MediaModule.Web/client/node_modules/@formatjs/ecma402-abstract/types/date-time").DateTimeFormatOptions' incorrectly extends interface 'Intl.DateTimeFormatOptions'.
  Types of property 'calendar' are incompatible.
    Type '"buddhist" | "chinese" | "coptic" | "ethiopia" | "ethiopic" | "gregory" | "hebrew" | "indian" | "islamic" | "iso8601" | "japanese" | "persian" | "roc" | undefined' is not assignable to type 'Calendar | undefined'.
      Type '"ethiopia"' is not assignable to type 'Calendar | undefined'.

1 export interface DateTimeFormatOptions extends Intl.DateTimeFormatOptions {
                   ~~~~~~~~~~~~~~~~~~~~~
```

I think you want to use `'ethiopic-amete-alem' | 'ethioaa'` instead of `'ethiopia'`

image

### Codesandbox URL

Please include a codesandbox URL if possible

### Reproducible Steps/Repo

1. Install `npm i react-intl typescript@rc`
2. import react-intl in some code
3. run `tsc`

## Expected behavior
No type issue with the upcoming TS release.

## Screenshots
N/A

## Desktop (please complete the following information):

- OS: N/A
- Browser N/A
- Version N/A

## Smartphone (please complete the following information):

- Device: N/A
- OS: N/A
- Browser N/A
- Version N/A

## Additional context
https://github.com/microsoft/TypeScript/issues/41601

### PR DESCRIPTION
**Pull request by kachkaev**
Fixes #2616

### CODE REVIEW

**Comment by longlho** [comment]
@kachkaev thanks a lot for the PR. I think since we currently only support `gregory` calendar that might be the correct restriction tbh.

**Comment by longlho** [comment]
@kachkaev would you mind changing the union to just `gregory` and see if that builds w/ TS4.2?

**Comment by kachkaev** [comment]
Sorry I did not understand your first comment. I thought you meant that we were OK with my original push given that other values are not used anyway.

I hope that switching to `gregory` only will do the job – see [TS playground with a similar example](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgGIHt3IN4ChkHJgAWoA5gFzIBEc1yAPjQEbW4C+uuoksiKAIThRkEAB6QQAEwDOaTDnyES5KrXoB6DcgDyAaQ5ce0eEmRCAXqIkRpcjFjyEipEJRoJN26FHRQOQA).

I’m unable to try the change locally ATM as I’m not on a work machine. The next time I’ll get access to the codebase I’ve spotted the problem in will be Monday.

**Comment by longlho** [comment]
@kachkaev it's ok as long as you can push your change I can verify it :) Thanks for the PR!

**Pull request merged**
