### PR TITLE
feat(vue-intl): use the same injection key for composition function and plugin

### PR DESCRIPTION
**Pull request by glen-84**
https://github.com/formatjs/formatjs/discussions/2924

### CODE REVIEW

**Comment by glen-84** [comment]
@longlho,

The problem with a symbol is that we have to export it to make it available to consumers.

[This](https://github.com/vuejs/vuex/blob/7744e74f50ff41fc7084466728f1a033610f43b5/src/injectKey.js) is what vuex does – they use a string, and also export it, so the consumer can either use the string, or import the key.

Which option do you prefer?

1. Follow vuex, and use a string (`export const intlKey = 'intl'`).
2. Just export a symbol, and the consumer will always need to import it when using `inject` (`inject: {intl: intlKey}`).

**Comment by longlho** [comment]
Let's export the symbol. Thanks a lot for the PR!

**Comment by glen-84** [comment]
This is a breaking change for anyone currently using `inject: ['intl']`. 😞

**Comment by glen-84** [comment]
@longlho,

What is your preference?

1. Release another major version.
2. Switch to option 1 above (the `'intl'` string), which will not be a breaking change.

**Comment by longlho** [comment]
Yeah bump major is fine by me. You don't have to bump manually just need to follow conventional changelog to declare breaking change

**Comment by glen-84** [comment]
> BREAKING CHANGE: The injection key is now a symbol and must be imported from `vue-intl`

Should I force-push an update to the commit message? (sorry about all the questions)

**Comment by longlho** [comment]
Yup

**Comment by glen-84** [comment]
@longlho,

I'm sorry to be a pain, but do you know roughly when this change might be released? 🙂

Thanks!

**Comment by longlho** [comment]
should be in like 10'

**Pull request merged**
