### PR TITLE
feat(@formatjs/intl-relativetimeformat): update shouldPolyfill for Intl.RelativeTimeFormat

### PR DESCRIPTION
**Pull request by romainmenke**
see [docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/RelativeTimeFormat#browser_compatibility)

Screenshot 2021-08-29 at 11 04 57

### CODE REVIEW

**Comment by romainmenke** [comment]
@longlho If there a way to get a bit more info on that CI failure? Then I can resolve the issues :)

**Comment by longlho** [comment]
```
==================== Test output for //packages/intl-relativetimeformat:prettier_prettier_test:
[warn] packages/intl-relativetimeformat/should-polyfill.ts
[warn] Code style issues found in the above file(s). Forgot to run Prettier?
================================================================================
```
so you just need to run `npm run format`

**Comment by longlho** [comment]
actually it's ok ill do that and merge this. Thanks!

**Comment by romainmenke** [comment]
Thank you!

Was just running it here, it needed to do a lot of a setup so it took a while :)

**Pull request merged**
