### PR TITLE
fix(@formatjs/icu-messageformat-parser): check "yu" regex option support with full regex

### LINKED ISSUE #2766: Crash through "Invalid RegExp: Invalid escape" in icu-messageformat-parser/parser.js
## Which package?
icu-messageformat-parser

## Describe the bug
We are using formatjs with react-intl in a react-native application that runs on Hermes on both android and iOS. All of the sudden react components using `intl.formatMessage` start to fail.
The error message looks like this:
```
(FATAL) GlobalErrorHandler: An uncaught exception occured. Invalid RegExp: Invalid escape 
```

and then there are many subsequent errors (like 400 of them), that all have the same in common:
```
 ERROR  [Error: [@formatjs/intl Error FORMAT_ERROR] Error formatting message: "ProfileCounters.experiences-counter", using default message as fallback. 
Locale: de
MessageID: ProfileCounters.experiences-counter
Default Message: {experiences, plural, one {Erlebnis} other {Erlebnisse}}
Description: Label for the number of experiences. This text is directly below the number. 
 

Cannot read property 'Parser' of undefined
TypeError: Cannot read property 'Parser' of undefined
```

So, for each error it says:
```
Cannot read property 'Parser' of undefined
TypeError: Cannot read property 'Parser' of undefined
```

These errors are all symptoms of the first error, as it fails to create the `parse` module. The stacktrace roughly looks this:
```
RE (parser.js:124:12)
<global> (parser.js:130:36)
<<some require calls, requiring parser.js>>
parse (index.js:32:22)
IntlMessageFormat (core.js:138:24)
formatMessage (message.js:89:29)
```

So, the error is thrown when it tries to call in the parser.js:
```
var matchIdentifierAtIndex;
if (REGEX_SUPPORTS_U_AND_Y) {
    // Native
    var IDENTIFIER_PREFIX_RE_1 = RE('([^\\p{White_Space}\\p{Pattern_Syntax}]*)', 'yu');
```

It seems that on the hermes engine new `RegExp('', 'yu')` doesn't throw, but `RegExp('([^\\p{White_Space}\\p{Pattern_Syntax}]*)', 'yu');` seems to throw.

We hotfixed this as of now by replacing the regex in the check:
```
var REGEX_SUPPORTS_U_AND_Y = true;
try {
    RE('([^\\p{White_Space}\\p{Pattern_Syntax}]*)', 'yu');
    //RE('', 'yu');
}
catch (_) {
    REGEX_SUPPORTS_U_AND_Y = false;
}
```

## To Reproduce

A reproduction could be:

1. Create a react native app using newest react native version
2. Use hermes engine instead of default engine
3. To the entry point of the app add once
```
const test = new RegExp("", "yu");
```
which should work
4. Change this to the pattern:
```
const test = new RegExp("([^\\p{White_Space}\\p{Pattern_Syntax}]*)", "yu");
```
which will cause the application to throw errors.

## Expected behavior
It shouldn't throw and do its job 😅   (sorry, I am really not into the internals of how all of this formatjs stuff works)

I think this might also be an issue related to the hermes engine. I will also open a ticket there

### PR DESCRIPTION
**Pull request by hannojg**
Fixes https://github.com/formatjs/formatjs/issues/2766

### CODE REVIEW

**Comment by hannojg** [comment]
Is this change enough, or do I need to run any build commands etc?

**Comment by hannojg** [comment]
Do you think this change will have any important impact on performance?

**Comment by longlho** [comment]
@hannojg nope shouldn't affect perf because this is run once when module is loaded.

**Comment by longlho** [comment]
Thanks a lot for your contributions!

**Pull request merged**
