### PR TITLE
up typescript v5

### PR DESCRIPTION
**Pull request by folt**
#4029  update typescript 5.0.0

### CODE REVIEW

**Comment by kachkaev** [comment]
I believe that it is also necessary to bump TypeScript in `peerDependencies`, where found. For example:

https://github.com/formatjs/formatjs/blob/ecf70f347241159aa785635e02d33d0f645d617f/packages/intl/package.json#L44-L46

↓

```ts
 "peerDependencies": { 
   "typescript": "^4.7 || 5" 
 },
```

Finally, `pnpm-lock.yaml` should be updated and committed too by running `pnpm install`.

**Comment by heath-freenome** [comment]
@folt You may also need to fix the `ts-transformer` package to support 5 as well

**Comment by folt** [comment]
Updated package.json for all projects

**Comment by longlho** [comment]
this diff upgrades a lot more than TS 5 which forces people to upgrade React and stuff as well, so FYI it won't be merged as is

**Comment by folt** [comment]
> this diff upgrades a lot more than TS 5 which forces people to upgrade React and stuff as well, so FYI it won't be merged as is

It's sad that you can't upgrade versions of other packages. Some by the way are already deprecated. I hope this will be taken into account in the future.

I corrected my pull request re and left only the typescript changes.

**Comment by longlho** [comment]
turns out to require a lot more work so did it myself. Closing this

**Pull request closed without merging**
