### PR TITLE
fix(@formatjs/ts-transformer): change ts-jest peer dependencies to be >= 27

### LINKED ISSUE #3629: Node 16 upgrade of ts-transformer breaks due to strict peerDependency
## Which package?
Since this is a monorepo. Please specify which package this bug report is for.

ts-transformer

## Describe the bug
The package has a peer dependency on `ts-jest@27` and my repo is using `ts-jest@28` which, when I do an upgrade to the latest version using node 16, it blows up as follows:
```
npm ERR! While resolving: @formatjs/ts-transformer@3.9.7
npm ERR! Found: ts-jest@28.0.3
npm ERR! node_modules/ts-jest
npm ERR!   dev ts-jest@"28.0.3" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peerOptional ts-jest@"27" from @formatjs/ts-transformer@3.9.7
npm ERR! node_modules/@formatjs/ts-transformer
npm ERR!   dev @formatjs/ts-transformer@"3.9.7" from the root project
npm ERR!   @formatjs/ts-transformer@"3.9.7" from babel-plugin-formatjs@10.3.23
npm ERR!   node_modules/babel-plugin-formatjs
npm ERR!     dev babel-plugin-formatjs@"10.3.23" from the root project
npm ERR!   1 more (eslint-plugin-formatjs)
npm ERR! 
npm ERR! Conflicting peer dependency: ts-jest@27.1.5
npm ERR! node_modules/ts-jest
npm ERR!   peerOptional ts-jest@"27" from @formatjs/ts-transformer@3.9.7
npm ERR!   node_modules/@formatjs/ts-transformer
npm ERR!     dev @formatjs/ts-transformer@"3.9.7" from the root project
npm ERR!     @formatjs/ts-transformer@"3.9.7" from babel-plugin-formatjs@10.3.23
npm ERR!     node_modules/babel-plugin-formatjs
npm ERR!       dev babel-plugin-formatjs@"10.3.23" from the root project
npm ERR!     1 more (eslint-plugin-formatjs)
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

## Expected behavior
Consider changing the `peerDependencies` for `ts-jest` in the `ts-transformer` package to be `>= 27` or eliminate it if it really isn't needed

### NOTE
I WAS able to work-around the issue by using `--legacy-peer-deps` but locking something like this down to one version of a common testing library seems problematic for future upgrades for people using `node 16`

### PR DESCRIPTION
**Pull request by heath-freenome**
Fix #3629 (again) 
- `ts-jest` just rev'd to version 29 to keep up with `jest`
- Made the peer dependency support any `ts-jest` version >= 27

### CODE REVIEW

**Comment by heath-freenome** [comment]
@longlho So, `ts-jest` rev'd to 29 and now the peer dependencies break for my project again. Fixed the peer dependencies so that it works and is more future flexible

**Comment by heath-freenome** [comment]
@longlho  Looks like there were heap issues in the tests?! Actually it looks like an issue for the tests in ALL of the current PRs... maybe you need to run your CI with the following to increase the default heap size:
```
      env:
        NODE_OPTIONS: --max_old_space_size=4096
```

**Comment by heath-freenome** [comment]
@longlho You fixed the build!!! Thanks! Looking forward to getting this in a release!

**Comment by heath-freenome** [comment]
@longlho I would love to get this released ASAP so I can get my builds working again

**Comment by heath-freenome** [comment]
@longlho Thanks for the merge. Any idea when the release containing this change will be ready?

**Comment by longlho** [comment]
I just cut a release last night

**Comment by heath-freenome** [comment]
I see it! It fixed things... Thank you

**Pull request merged**
