### PR TITLE
Update tzdata to 2022g

### PR DESCRIPTION
**Pull request by davidseek**
I have updated `tzdata` to `2022g` as described in the [CONTRIBUTION Wiki](https://github.com/formatjs/formatjs/blob/main/CONTRIBUTING.md#updating-tzdata-version), including updating the sha and running the Bazel script. The Commit is the result of that script.

### CODE REVIEW

**Comment by adam-felix-shopify** [comment]
Since I created my issue, I see that tzdata has been updated to 2023c.  Would it make sense to update to that one instead of 2022c?

**Comment by davidseek** [comment]
This is the update I specifically need, because the changes from 2022g are now live, and breaking timezones. Feel free to cut a follow up PR with the later version.

**Comment by davidseek** [comment]
I am specifically looking for the 2022g change right now. I will cut a follow up PR with 2023c (or latest). But I'm kind of confused why the Automation steps seem to take a week+...

**Comment by longlho** [comment]
Will take a look soon. Thanks for the contribution!

**Comment by longlho** [comment]
I merged this manually. Thanks a lot for your contribution!

**Comment by davidseek** [comment]
@adam-felix-shopify, I have created this PR for you https://github.com/formatjs/formatjs/pull/4065

**Pull request closed without merging**
