### PR TITLE
fix(@formatjs/cli): bump fast-glob to 3.2.7

### LINKED ISSUE #3027: formatjs/cli extract not using ignore option
## Which package?
@formatjs/cli

## Describe the bug
Running extract command 
`npx @formatjs/cli extract --throws '../**/src/**/*.{ts,tsx}' --ignore '../**/src/**/*.{d,test}.{ts,tsx}' --out-file 'pre-translate/en_US.json' --format './formatjs/formatter.js'`
 throws an error
```
Error: Error processing file ../web-main/packages/web/src/@types/logger.d.ts 
Debug Failure. Output generation failed
    at Object.transpileModule (/Users/andeliv/.npm/_npx/68309/lib/node_modules/@formatjs/cli/node_modules/typescript/lib/typescript.js:135663:29)
    at /Users/andeliv/.npm/_npx/68309/lib/node_modules/@formatjs/cli/src/parse_script.js:16:43
    at processFile (/Users/andeliv/.npm/_npx/68309/lib/node_modules/@formatjs/cli/src/extract.js:55:9)
    at /Users/andeliv/.npm/_npx/68309/lib/node_modules/@formatjs/cli/src/extract.js:96:59
    at step (/Users/andeliv/.npm/_npx/68309/lib/node_modules/@formatjs/cli/node_modules/tslib/tslib.js:143:27)
    at Object.next (/Users/andeliv/.npm/_npx/68309/lib/node_modules/@formatjs/cli/node_modules/tslib/tslib.js:124:57)
    at fulfilled (/Users/andeliv/.npm/_npx/68309/lib/node_modules/@formatjs/cli/node_modules/tslib/tslib.js:114:62)
```
It started failing ~4 days ago, before that `--ignore` seemed to work fine.

### Reproducible Steps/Repo
https://github.com/andeliv/formatjs-cli-error

1) cd packages/trn
2) yarn intl:extract-all
3) see the error `Error: Error processing file ../web-main/packages/web/src/@types/logger.d.ts`

After removal of the `logger.d.ts` file all messages from both packages are extracted correctly

## Expected behavior
Strings are extracted from all packages and files from `--ignore` option are ignored

### PR DESCRIPTION
**Pull request by chenrui333**
fixes #3027

### CODE REVIEW

**Comment by chenrui333** [comment]
cc @longlho 🙏

**Comment by longlho** [comment]
Can you update the cli package.json as well?

**Comment by chenrui333** [comment]
I see, updating it now.

**Comment by chenrui333** [comment]
@longlho 👋  anything else needs to be done for this PR? Thanks!

**Comment by longlho** [comment]
Thanks a lot for your contributions!

**Comment by chenrui333** [comment]
Thanks @longlho! 👍

**Pull request merged**
